// -----------------------------------------------------------------------------
// HANDWRITTEN GENERATOR SCRIPT
//
// File       : dev/tools/reset/reset.db.js
// Purpose    : Resets development SQL databases for all configured dialects.
// Writes     : backend/data/sql/data.db (sqlite), configured Postgres database.
// Reads      : .env (DB_DIALECT_LIST, POSTGRES_*), dev/db/*/*.sql.
// Notes      : Uses external CLIs (sqlite3, psql). Destructive – dev use only.
// -----------------------------------------------------------------------------

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { spawnSync } from 'child_process';
import { createStepLogger } from '../../generators/_logger.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname  = path.dirname(__filename);

// Project root = three levels up from /dev/tools/reset
const PROJECT_ROOT = path.resolve(__dirname, '..', '..', '..');

// Create logger immediately so the banner is printed first
const log = createStepLogger({
  step: 'reset-db',
  title: 'Database Reset',
  generatorPath: 'dev/tools/reset/reset.db.js',
  projectRoot: PROJECT_ROOT,
});

// -----------------------------------------------------------------------------
// Helpers
// -----------------------------------------------------------------------------

/**
 * Minimal .env loader: populates process.env from PROJECT_ROOT/.env if present.
 * Does nothing if the file is missing (e.g., before gen:env has ever run).
 */
function loadEnvFromFile() {
  const envPath = path.join(PROJECT_ROOT, '.env');
  if (!fs.existsSync(envPath)) {
    return;
  }

  const contents = fs.readFileSync(envPath, 'utf8');
  for (const line of contents.split(/\r?\n/)) {
    if (!line || !line.trim() || line.trim().startsWith('#')) {
      continue;
    }

    const idx = line.indexOf('=');
    if (idx === -1) {
      continue;
    }

    const key = line.slice(0, idx).trim();
    const value = line.slice(idx + 1).trim();

    if (key && !(key in process.env)) {
      process.env[key] = value;
    }
  }
}

/**
 * Resolve active SQL dialects from environment.
 * Contract: DB_DIALECT_LIST is generated by dev/generators/generate.env.js.
 * Fallback: "sqlite" if nothing is configured (safe for early dev).
 */
function resolveDialects() {
  const raw =
    process.env.DB_DIALECT_LIST ||
    process.env.DB_DIALECTS ||
    'sqlite';

  return raw
    .split(',')
    .map((value) => value.trim().toLowerCase())
    .filter(Boolean);
}

/**
 * Require a given environment variable to be present.
 * Throws with a clear message if missing.
 */
function requiredEnv(name) {
  const value = process.env[name];
  if (!value) {
    throw new Error(`Missing required environment variable: ${name}`);
  }
  return value;
}

/**
 * Run a shell command and log it as a "run" action.
 * - command: actual command string executed
 * - displayLabel: shorter pretty version for logs (optional)
 * Throws if the command exits with a non-zero status.
 */
function runCommand(command, options = {}, displayLabel) {
  const label = displayLabel || command;
  log.run(label);

  const result = spawnSync(command, {
    shell: true,
    stdio: 'inherit',
    ...options,
  });

  if (result.status !== 0) {
    throw new Error(`Command failed (exit code ${result.status})`);
  }
}

/**
 * Run a shell command with additional environment variables.
 */
function runWithEnv(command, extraEnv = {}, displayLabel) {
  const env = {
    ...process.env,
    ...extraEnv,
  };

  runCommand(command, { env }, displayLabel);
}

// -----------------------------------------------------------------------------
// SQLite Reset
// -----------------------------------------------------------------------------

function resetSqlite() {
  const dbPath = path.join(PROJECT_ROOT, 'backend', 'data', 'sql', 'databases', 'finance.db');
  const schemaSql = path.join(PROJECT_ROOT, 'dev', 'db', 'sqlite', 'sqlite.schema.sql');
  const seedSql = path.join(PROJECT_ROOT, 'dev', 'db', 'sqlite', 'sqlite.seed.sql');

  const relDbPath     = path.relative(PROJECT_ROOT, dbPath) || dbPath;
  const relSchemaPath = path.relative(PROJECT_ROOT, schemaSql) || schemaSql;
  const relSeedPath   = path.relative(PROJECT_ROOT, seedSql) || seedSql;

  log.kv('dialect', 'sqlite');
  log.kv('sqlite.db', relDbPath);

  if (fs.existsSync(dbPath)) {
    fs.unlinkSync(dbPath);
    log.delete(relDbPath);
  }

  const sqliteCli = 'sqlite3';

  // Use short, relative labels in logs; execute absolute paths under the hood.
  runCommand(
    `"${sqliteCli}" "${dbPath}" < "${schemaSql}"`,
    {},
    `sqlite3 ${relDbPath} < ${relSchemaPath}`,
  );

  runCommand(
    `"${sqliteCli}" "${dbPath}" < "${seedSql}"`,
    {},
    `sqlite3 ${relDbPath} < ${relSeedPath}`,
  );
}

// -----------------------------------------------------------------------------
// PostgreSQL Reset
// -----------------------------------------------------------------------------

function resetPostgres() {
  // Single source of truth: values generated into .env by generate.env
  const PSQL_BIN    = requiredEnv('POSTGRES_PSQL_BIN');
  const PG_HOST     = requiredEnv('POSTGRES_DB_HOST');
  const PG_PORT     = requiredEnv('POSTGRES_DB_PORT');
  const PG_DATABASE = requiredEnv('POSTGRES_DB_NAME');
  const PG_USER     = requiredEnv('POSTGRES_DB_USER');
  const PG_PASSWORD = requiredEnv('POSTGRES_DB_PASSWORD');

  const SCHEMA_SQL = path.join(PROJECT_ROOT, 'dev', 'db', 'postgres', 'postgres.schema.sql');
  const SEED_SQL = path.join(PROJECT_ROOT, 'dev', 'db', 'postgres', 'postgres.seed.sql');

  const relSchemaPath = path.relative(PROJECT_ROOT, SCHEMA_SQL) || SCHEMA_SQL;
  const relSeedPath   = path.relative(PROJECT_ROOT, SEED_SQL) || SEED_SQL;

  log.kv('dialect', 'postgres');
  log.kv('postgres.db', PG_DATABASE);

  const extraEnv = {
    PGPASSWORD: '********', // masked in env we pass to logger, real value in process.env
  };

  // Real env for psql (password must be present)
  const realEnv = { PGPASSWORD: PG_PASSWORD };

  // psql flags:
  // -q                : quiet (suppress BEGIN/DROP/etc chatter)
  // -v ON_ERROR_STOP=1: stop on first error and return non-zero exit code
  const baseFlags = `-q -v ON_ERROR_STOP=1 -h "${PG_HOST}" -p "${PG_PORT}" -U "${PG_USER}" -d "${PG_DATABASE}"`;

  // Schema
  runWithEnv(
    `"${PSQL_BIN}" ${baseFlags} -f "${SCHEMA_SQL}"`,
    { PGPASSWORD: PG_PASSWORD },
    `psql -d ${PG_DATABASE} -f ${relSchemaPath}`,
  );

  // Seed
  runWithEnv(
    `"${PSQL_BIN}" ${baseFlags} -f "${SEED_SQL}"`,
    { PGPASSWORD: PG_PASSWORD },
    `psql -d ${PG_DATABASE} -f ${relSeedPath}`,
  );
}

// -----------------------------------------------------------------------------
// Main
// -----------------------------------------------------------------------------

function main() {
  try {
    loadEnvFromFile();

    log.kv('root', PROJECT_ROOT);

    const dialects = resolveDialects();
    log.kv('dialects', dialects.join(', '));

    for (const dialect of dialects) {
      if (dialect === 'sqlite') {
        resetSqlite();
      } else if (dialect === 'postgres') {
        resetPostgres();
      } else {
        log.kv('dialect', dialect);
        log.write(`skip     : unsupported dialect "${dialect}"`);
      }
    }

    log.success();
  } catch (err) {
    log.failure(err);
    process.exit(1);
  }
}

main();

// -----------------------------------------------------------------------------
// End of generator script: reset.db
// -----------------------------------------------------------------------------
